name: release-windows

on:
  push:
    tags: ["v*.*.*"] # e.g. v0.1.7
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write # allow publishing to GitHub Releases
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # used by electron-builder to publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Setup Python (for node-gyp if needed)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (clean)
        run: npm ci

      # Build renderer + main + preload with electron-vite
      - name: Build (electron-vite)
        run: npm run build

      # Package AND publish to the Release for this tag
      - name: Package & publish (electron-builder)
        run: npm run build:win
