name: release-windows

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (clean)
        run: npm ci
        # postinstall -> scripts/install-app-deps.mjs will run automatically

      - name: Build (electron-vite)
        run: npm run build

      - name: Package (electron-builder)
        run: npm run build:win

      - name: List artifacts
        run: |
          dir dist
          dir dist\win-unpacked

      - name: Create Release & upload assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/**/*.exe
            dist/**/*.zip
            dist/**/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
